# Generated by Django 4.1.2 on 2022-11-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.URLField(blank=True),
        ),
    ]
